FROM nginx:latest
# make sure to copy the proxy.conf file to this specific location in your Docker image for the proxy server: /etc/nginx/conf.d/default.conf.
COPY proxy.conf /etc/nginx/conf.d/default.conf